### ISSUE TITLE
Search in Narrative (wikidata items)

### ISSUE THREAD

**Issue by MiklerGM** [chronhq/frontend#10]
Extends #9 

Look through labels and descriptions of wikidata items listed in `attached_events` or listed in `WikidataStore` while searching

**Comment by MiklerGM** [comment]
We can't perform search on `attached_items` because it's a `cached_table` ids. Not the wikidata items

**Comment by whirish** [comment]
If you want I can nest data to gave it return the cached table instances as JSON rather than just the IDs

**Comment by MiklerGM** [comment]
@whirish it would be great, thanks.
