### ISSUE TITLE
New naming

### ISSUE THREAD

**Issue by faultcore** [chronhq/frontend#11]
This is an issue about new project name. Please leave your suggestions in comments (one idea - one comment). Apply +1/-1 for all comments.
- `name`: How should it be called?
- `shortname`: If relevant, a shorter version of the name
- `description`: Its meaning
- `available urls`: Some examples of domain names that are available. You can use namecheap.com to find them.
- `social media presence`:  Some examples of handles that are available. You can use https://namechk.com/ to find them.
- `google search`: is something big already coming up when we search for `name`?

**Comment by amaurymartiny** [comment]
Some additional notes:
- you'll need a Github account to propose ideas
- prefer an actual proposal than a general idea.
    - **Don't**: "an idea could be concatenating a greek work and an esperanto one"
    - **Do**: Write 3 proposal, for "ChronoScio", "ChronoMapo", "ChronoLibro", and in the descriptions, write this idea
    - it's still allowed to write non-proposal comments, (e.g. to comment on another proposal) but when possible, come up with a proposal
- only use +1, i.e. the one under this comment. Other emojis will not be taken into account.
- if one of the proposals here has 51% of upvotes from participating users, we'll take it. If not, we'll take the n most popular ones, and make a Slack/Discord poll
- if there's a particular logo you'd like to match with your name, please post the link to #12 in your proposal

**Comment by faultcore** [comment]
- mapsof.world
- currently on sale starting 18 Eur.
<img width="1292" alt="2018-12-21 13 01 43" src="https://user-images.githubusercontent.com/156677/50341804-9e091b00-0520-11e9-98b4-545bd49c2453.png">

**Comment by amaurymartiny** [comment]
Copying ideas from https://github.com/chronoscio/frontend/issues/2

- `name`: The Humanity
- `description`: It sounds like a big, generic name. Our project is, in a sense, about all humanity.
- `available urls`: thehumanity.net, thehumanity.io, thehumanity.co
- `social media`: thehumanityapp is availble ([here](https://www.namecheck.com/search/?searchterm=thehumanityapp)), thehumanityhq too ([here](https://www.namecheck.com/search/?searchterm=thehumanityhq))
- `google search`: apart from some definitions, "Oh, the Humanity!" comes up. It's not the best, but doable.

**Comment by faultcore** [comment]
- expatlas
- expatlas.com/net/org all available for about $10
- rich availability in social media
- something between exploring and atlas (we already got a joke about expats also)

**Comment by faultcore** [comment]
- explography
- explography.org/info/net/co/io available for about $10
- mostly available in social media (not on facebook tho)
- generated from exploring and geography

**Comment by amaurymartiny** [comment]
- name: `Ortelius`
- description: It’s the Latinized name of Abraham Ortels. Ortelius was a famous 16th century geographer who made the Theatrum Orbis Terrarum. He also made the first historical atlas.
- url: mostly taken, `ortelius.app` and `ortelius.co` are available.
- social media: taken, it needs to be `orteliusapp` or `orteliushq`
- google search: apart from the cartographer, there's a GIS software, but nothing big, so okay.

credits @jpeppelman

**Comment by amaurymartiny** [comment]
- name: `fabulis terrarum`
- shortname: `fabulis`?
- description: "Earth's stories" in latin
- url: fabulisterrarum.org
- social media: taken, it needs to be `fabulisterrarumapp` or `fabulisterrarumhq`
- google search: we're good.

credits @bapo224 (I think?)

**Comment by amaurymartiny** [comment]
- name: WikiAtlas
- description: Wiki and Atlas together
- url: atlas.wiki, wikiatlas.com (expensive), wikiatlas.net
- social media: mostly not taken (twitter is though)
- google search: we're good, there's a wikipedia "portal", but I think it's not a big deal

**Comment by Delh** [comment]
It's not just about spatio dimension after all, so perhaps something like:

atlastemporum.wiki $19.99
atlastemporum.com $0.99

It's a bit long, but on a positive note a lot of people will understand what's going on with the name, especially in the case of the .wiki.

**Comment by MiklerGM** [comment]
name: Age Of Maps
url: ageofmaps.com (high availability)
social: free 99%
google: some threads and articles nothing serious

**Comment by MiklerGM** [comment]
~name: unclaimed.world~
That one is funny, but it's already taken.

I was thinking about new keywords for naming and I noticed that some of the proposed names, except `The Humanity` and `fabulis` are about time (chron|temp), maps(atlas) or famous people who were drawing maps in the past. We can try to use words like colonization, conquest, crusades, frontier, etc.

**Comment by faultcore** [comment]
name: Chron
url: chronmaps.com ($10)
Chron is available on facebook, youtube. Chronmaps is of very high availability in social media.
Google: newspaper, musical album, R package

**Comment by MiklerGM** [comment]
Title | Votes | status
-- | -- | --
Chronmaps | 3 | approved
Ortelius | 4 | disqualified
mapsof.world | 4 |  disqualified

Everyone else got 1 up vote
