### ISSUE TITLE
New logo

### ISSUE THREAD

**Issue by faultcore** [chronhq/frontend#12]
This is an issue about new project logo. Please leave your suggestions in comments (one idea - one comment). Apply +1/-1 for all comments.

**Comment by faultcore** [comment]
![whatsapp image 2018-12-13 at 17 54 44](https://user-images.githubusercontent.com/156677/50374762-e3e2e380-05f3-11e9-9510-ad050f14093b.jpeg)
Made by our illustrator

**Comment by faultcore** [comment]
![2018-12-13 16 17 59](https://user-images.githubusercontent.com/156677/50374771-0117b200-05f4-11e9-9dc7-02086a93a3a5.jpg)
Made by our illustrator

**Comment by faultcore** [comment]
![whatsapp image 2018-12-13 at 17 54 45](https://user-images.githubusercontent.com/156677/50374792-1987cc80-05f4-11e9-922b-003f649eef14.jpeg)
Made by our illustrator, more of a gaming direction

**Comment by MiklerGM** [comment]
Logo combined with name from #11 

![chronmaps](https://user-images.githubusercontent.com/61106/53284366-a44f8980-3753-11e9-80fa-c9bdebcc1b45.png)
