### ISSUE TITLE
"about us" page with icons on the world map

### ISSUE THREAD

**Issue by faultcore** [chronhq/frontend#15]
There is an idea to put everyone participating in the project on the map to show how international our team is. It can basically look like the draft 
![ppl](https://user-images.githubusercontent.com/156677/50529213-a995ac80-0af3-11e9-9117-77949d12a957.png)
For now only icons (no names or any other data, but this is rather discussable). We will be adding everyone who filled the team list on GoogleDoc, however if anyone else wants to join - please write your country and city in the comments below.

**Comment by MiklerGM** [comment]
I propose to use `/about` url.

Probably we should change year to 2019 (or latest mapped year in Global Narrative)?

Instead of `Global Narrative` title would be 'About Us`, correct?
No tooltips on pins, only small information field in left dashboard above footer.
How it should look like if we have a scroll bar for narratives list?

**Comment by faultcore** [comment]
Updated version
![ppl2](https://user-images.githubusercontent.com/156677/51077603-38d0c180-16a9-11e9-80c1-ba3056f99da2.png)

**Comment by MiklerGM** [comment]
Currently added: 1 point per city
```javascript
  { x: 33.044167, y: 34.674722 }, // Limassol
  { x: -122.416667, y: 37.783333 }, // San Francisco
  { x: 2.3508, y: 48.8567 }, // Paris
  { x: 37.616667, y: 55.75 }, // Moscow
  { x: 30.308611, y: 59.9375 }, // Saint-Petersburg
  { x: -71.063611, y: 42.358056 }, // Boston
  { x: 32.866667, y: 39.933333 }, // Turkey
  { x: -93.093611, y: 44.944167 }, // Minnesota
  { x: 4.9, y: 52.366667 }, // Amsterdam
  { x: 5.783333, y: 53.2 }, // Leeuwarden
  { x: 13.388889, y: 52.516667 }, // Berlin
  { x: -122.272778, y: 37.871667 }, // Berkeley
```

**Comment by faultcore** [comment]
As proposed by the team we add a timeline (same as in narrative)
**7 March 2017** - Chronist team launched first demo
**11 November 2017** - first narrative made by Chronist
**12 January 2018** - the launch of the first slack and the ChronoScio project announced by Ollie Bye
**6 July 2018** - ChronoScio team launched first demo
**1 August 2018** - Chronist team published 220 years of world history maps
**9 September 2018** - ChronoScio team began mapping past 1789
**19 October 2018** - ChronoScio and Chronist teams came together
**26 February 2019** - united Chron team launched first demo
