### ISSUE TITLE
On click balloon with sources

### ISSUE THREAD

**Issue by faultcore** [chronhq/frontend#16]
Two types of behavior for balloons: on hover and on click.
On the country/region level 

- on hover we see Name, flag, coat-of-arms
- on click we see all the above plus Data origin and Source. Data origin has links to the wikidata id's used. Source has links to space-time volume sources.

On hover
![on hover](https://user-images.githubusercontent.com/156677/50562482-6db83e00-0cd1-11e9-86e1-39c935ff1401.png)
On click
![onclick](https://user-images.githubusercontent.com/156677/50562428-131ee200-0cd1-11e9-912e-a6c68009d25a.png)

**Comment by MiklerGM** [comment]
Sample JSON
```
{
  "title": "United Kingdom of Great Britain and Northern Ireland",
  "flag": "https://upload.wikimedia.org/wikipedia/commons/a/ae/Flag_of_the_United_Kingdom.svg",
  "emblem": "https://upload.wikimedia.org/wikipedia/commons/9/98/Royal_Coat_of_Arms_of_the_United_Kingdom.svg",
  "dataOrigin": ["https://www.wikidata.org/wiki/Q145"],
  "sources": [
    "https://en.wikipedia.org/wiki/United_Kingdom",
    "https://www.wikidata.org/wiki/Q145"
  ]
}
```

Maybe we should add one more line with deeper level of administrative region e.g:
```
subTitle: "Scotland"
```

**Comment by MiklerGM** [comment]
Images are shown only on click event, because of some performance issues

**Comment by MiklerGM** [comment]
Result with click coordinates
![image](https://user-images.githubusercontent.com/61106/52350306-8d592980-2a28-11e9-9610-be09860d9fed.png)
