### ISSUE TITLE
Select wikidata properties according to date

### ISSUE THREAD

**Issue by MiklerGM** [chronhq/frontend#21]
Some of wikidata properties can have a reference to a different points in time.

Few good examples of Political Entities with some historical data
[Egypt](https://www.wikidata.org/wiki/Q79) 
[USA](https://www.wikidata.org/wiki/Q30)
[Ottoman Empire](https://www.wikidata.org/wiki/Q12560)
[Russian Empire](https://www.wikidata.org/wiki/Q34266)

- [x] [flag images P41](https://www.wikidata.org/wiki/Property:P41) are must-have for #16 
- [x] [capital P36](https://www.wikidata.org/wiki/Property:P36)
- [x] [head of government P6](https://www.wikidata.org/wiki/Property:P6)
- [x] [population P1082](https://www.wikidata.org/wiki/Property:P1082)
- [x] [basic form of government P122](https://www.wikidata.org/wiki/Property:P122)

We don't need HDI and GDP and other for now...

**Comment by faultcore** [comment]
<img width="557" alt="screenshot 2019-02-05 19 35 44" src="https://user-images.githubusercontent.com/156677/52295907-46622a00-297d-11e9-8710-d4c115aed379.png">
Like this maybe?
