### ISSUE TITLE
Data models cleaning before migration

### ISSUE THREAD

**Issue by faultcore** [chronhq/frontend#30]
Delete pins and related components, layers

- [x] cities
- [x] geo events 
- [x] actors
- [x] inventions
- [x] delete old types in balloons 

Delete course models

- [x] course traces
- [x] course geopoints  
- [x] delete localization toggle

Migrate

- [x] loading of narratives
- [x] course timelines to narrations
- [x] courses to narratives

**Comment by MiklerGM** [comment]
Basic migration is done.

What else todo:

- [ ] Fix start-end dates for courses https://github.com/chronhq/backend/issues/54
- [ ] Add Map Settings support and fix #14 
- [ ] Fetch Political Relations
- [ ] Select TE for STV based on the PRs.
- [ ] Add search in narrations attached items
- [ ] Add search in narratives tags
- [ ] Fix new UI issues
