### ISSUE TITLE
Pins without coordinates

### ISSUE THREAD

**Issue by faultcore** [chronhq/frontend#31]
How do we deal with pins that doesn't have any coordinates? 
In Chronist we had such events and put these also as pins in bottom left corner. If we decide to keep it we need an endpoint on backend to provide a response with event type and WIkidata id by year.

![image 2019-02-06 16 36 08](https://user-images.githubusercontent.com/156677/52352658-4faacf80-2a2d-11e9-97fd-d47dbfb96efb.jpg)

**Comment by whirish** [comment]
I support the corner implementation. I can update the CD model to make the location optional if the consensus is in support
