### ISSUE TITLE
Demo stuck on loading screen

### ISSUE THREAD

**Issue by ataalik** [chronhq/frontend#47]
Currently for some people demo gets stuck in the loading screen. The historical country borders are loaded but the actual map tiles like the ocean are not. Present in both Chromium and Firefox. 
![image](https://user-images.githubusercontent.com/5862754/53702055-20ad3100-3e14-11e9-9028-35f290c3c40b.png)

The error from the console: 

```
mapbox-gl.js:28 Uncaught RangeError: out of range source coordinates for image copy
    at Ua (mapbox-gl.js:28)
    at Function.qa.copy (mapbox-gl.js:28)
    at u (mapbox-gl.js:32)
    at eval (mapbox-gl.js:32)
    at Image.o.onload (mapbox-gl.js:28)
```

**Comment by MiklerGM** [comment]
According to this, it might be an issue with devicePixelRatio
https://github.com/mapbox/mapbox-gl-js/issues/5860

Could you check and find sprite image in the networking tab?
![image](https://user-images.githubusercontent.com/61106/53735121-f8ddbd80-3e53-11e9-8b45-6cc2618d0492.png)

**Comment by ataalik** [comment]
It seems the these two files are fetched correctly on the latest deployed code.
