### ISSUE TITLE
Solid border line (stroke)

### ISSUE THREAD

**Issue by MiklerGM** [chronhq/frontend#51]
Add stroke to borders

That will require some changes on the backend or in the APs MVT

**Comment by whirish** [comment]
This would be a nice cosmetic change. Is the proposal to have the backend calculate and return the perimeter in the MVT?

**Comment by MiklerGM** [comment]
There are some ways, how we can do this. Each of them requires us to build a `union` or `collection` of atomic polygons to get the outer boundaries of territory.

- stroke option in MVT style
- separate MVT layer with lines

---
### stroke option in MVT style

We could enable stroke for each polygon that should be shown on map. The stroke style would be the same for each polygon shown on one Mapbox Layer. _However we can add more than one layer with different filter options._

In this case we should use _union_ or _collection_ of atomic polygons inside MVT

We can enable stroke on prod by doing this `window.store.mapStyle.atomicBorders.debug = true`
![image](https://user-images.githubusercontent.com/61106/53852514-836f0b80-3f7f-11e9-8462-a1df678c92ba.png)

---
### separate MVT layer with lines

This can be done is several ways (ST_Boundary on collection or topology way)
That would allow us to use different styles for borders on one layer.

**Comment by MiklerGM** [comment]
I would personally prefer to go with stroke and full STVs in MVT. _Styled lines can be generated from the same source._

Pros of going with stroke option
- Less computations on filtering
- All the information from STV would be in MVT, so we do not need to fetch STV's
- White lines _inside_ territory would no longer bother us 
![image](https://user-images.githubusercontent.com/61106/53853575-46a51380-3f83-11e9-98db-1157f76e76bc.png)

Cons:
- Union will take more space in the DB (500mb instead of 20mb)
- AP are present only for validation purposes

Side effects
- mbtiles will be the ~ same size
- style will no longer fail if STVs would have an overlapping
