### ISSUE TITLE
SPARQL query for wikidata

### ISSUE THREAD

**Issue by MiklerGM** [chronhq/frontend#52]
It might be better for optimization to perform sparql request instead of fetching wikidata entities by id

**Comment by whirish** [comment]
I thought we had found earlier that querying the wikidata API directly was too slow?

**Comment by MiklerGM** [comment]
We are fetching wikidata entities directly by id right now.

Complex queries with bboxes are slow, but we already have the IDs

**Comment by MiklerGM** [comment]
[Example ](https://query.wikidata.org/#SELECT%20%3FitemLabel%20%3Fflag%20%3Fcapital%20%3FcapitalLabel%20%3Fstarttime%20%3Fendtime%20%3Fstarttime1%20%3Fendtime1%20%3FheadOfGovernment%20%3FheadOfGovernmentLabel%20%3Fstarttime2%20%3Fendtime2%20%3Fhead_of_government%20%3Fhead_of_governmentLabel%20WHERE%20{%20%20BIND(wd%3AQ30%20AS%20%3Fitem)%20%20OPTIONAL%20{%20%20%20%20%3Fitem%20p%3AP41%20%3Fstatement.%20%20%20%20%3Fstatement%20ps%3AP41%20%3Fflag.%20%20%20%20OPTIONAL%20{%20%3Fstatement%20pq%3AP580%20%3Fstarttime.%20}%20%20%20%20OPTIONAL%20{%20%3Fstatement%20pq%3AP582%20%3Fendtime.%20}%20%20}%20%20OPTIONAL%20{%20%20%20%20%3Fitem%20p%3AP36%20%3Fstatement1.%20%20%20%20%3Fstatement1%20ps%3AP36%20%3Fcapital.%20%20%20%20OPTIONAL%20{%20%3Fstatement1%20pq%3AP580%20%3Fstarttime1.%20}%20%20%20%20OPTIONAL%20{%20%3Fstatement1%20pq%3AP582%20%3Fendtime1.%20}%20%20}%20%20OPTIONAL%20{%20%20%20%20%3Fitem%20p%3AP6%20%3Fstatement2.%20%20%20%20OPTIONAL%20{%20%3Fitem%20wdt%3AP6%20%3Fhead_of_government.%20}%20%20%20%20OPTIONAL%20{%20%3Fstatement2%20pq%3AP580%20%3Fstarttime2.%20}%20%20%20%20OPTIONAL%20{%20%3Fstatement2%20pq%3AP582%20%3Fendtime2.%20}%20%20}%20%20SERVICE%20wikibase%3Alabel%20{%20bd%3AserviceParam%20wikibase%3Alanguage%20"en".%20}}ORDER%20BY%20(%3Fstarttime)%20(%3Fstarttime1)%20(%3Fstarttime2))of query to fetch heads of government, capitals and flags for USA.

It's one megabyte of data, cross join is not the best option here

**Comment by MiklerGM** [comment]
Comparing to 800kb of [API ](https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q30&format=json&languages=ru%7Cen&origin=*) response it is not that bad

[api-result.zip](https://github.com/chronhq/frontend/files/3101483/api-result.zip)
