### ISSUE TITLE
Full STV info in MVT

### ISSUE THREAD

**Issue by MiklerGM** [chronhq/frontend#55]
I would personally prefer to go with stroke and full STVs in MVT. _Styled lines can be generated from the same source._

Pros of going with stroke option
- Less computations on filtering
- All the information from STV would be in MVT, so we do not need to fetch STV's
- White lines _inside_ territory would no longer bother us 
![image](https://user-images.githubusercontent.com/61106/53853575-46a51380-3f83-11e9-98db-1157f76e76bc.png)

Cons:
- Union will take more space in the DB (500mb instead of 20mb)
- AP are present only for validation purposes

Side effects
- mbtiles will be the ~ same size
- style will no longer fail if STVs would have an overlapping

_Originally posted by @MiklerGM in https://github.com/chronhq/frontend/issues/51#issuecomment-469953110_

**Comment by MiklerGM** [comment]
@v1kun @whirish 
After joining APs in MVT there are some unwished lines
![image](https://user-images.githubusercontent.com/61106/54484342-cdd37080-483a-11e9-88f2-dae2d966cd85.png)

**Comment by v1kun** [comment]
ouch, that's bad, but it looks like almost the same as before cleaning of small overused polygons (APs used in several STVs)
using topology might help, imo.

**Comment by MiklerGM** [comment]
It might be the problem of simplification or with splitting and joining territories or with ST_Collect.

While zoomed in almost all of them are gone.

With topology we will never split our polygons. It might help.

**Comment by MiklerGM** [comment]
It can be caused by ST_Buffer (changing the precision of data)
